# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  database: postgres
  username: rails
  password: password
  pool: 5
  timeout: 5000
  host: localhost
  #port: 5432

#test:
#  adapter: postgresql
#  host: localhost
#  username: user
##  password: emoneuro
#  database: postgres
#  host: localhost
#  port: 5432

